### ISSUE TITLE
Function NEXT_STEP_TYPE and NEXT_MULTISTEP_EXISTS always return 'simple-step' and false

### ISSUE THREAD

**Issue by madmexx2002** [mt-ag/apex-flowsforapex#104]
Hi,

**thx for this fantastic app, love it.**

When i use the application helper functions i didn't get the excpected result. 

![image](https://user-images.githubusercontent.com/36326420/103457760-671a9200-4d02-11eb-9622-449bf30c7423.png)

At this point the functions always say 'single-step' or next_multistep_exists => false.
I took the SBFL_ID and SBFL_PRCS_ID from the view FLOW_TASK_INBOX_VW.

happy new year, Mark

**Comment by rallen2010** [comment]
Hi Mark,

Glad you're enjoying Flows for APEX.

The 'single step ' and next step is multistep helpers are left over from V4 and are obsolete in V5 of Flows for APEX.  They WERE there to help you get around the V1 - V4 API which had 2 calls for advancing a process -- flow_next_step usually, and flow_next_branch for Exclusive and Inclusive Gateways, where the user supplied instructions on which way the gateway should route the process.
In V5, we changed and corrected a few things.
- gateways aren't the steps where decisions should be taken.  instead they route the process based on decisions already made.  Now they look up routing information in a process variable (named <gateway_id>||':route'). the process variable should contain the id's of the flow or flows to be taken.  Failing that, they check for a default path.  Failing that, they error.
- all process advancement is now done with flow_complete_step(process_id, Subflow_id).  No need for the UI to know whether the next step is multistep or not.

Apologies for not tidying up the API file better in the 5.0.0 & 5.0.1 release.  I did, however, just clean it up earlier this week, marking the multistep functions as deprecated & for removal so it will be bettering the next release we make.

BTW - they are fixed to always return false so that any apps that were made for V4 now won't stop to ask the user for instructions at a gateway.

**Comment by rallen2010** [comment]
see #101

**Comment by madmexx2002** [comment]
Hi Richard,

thx for the fast answer. 

Your right, gateways aren't the steps where decissions should be taken. It's the task. If application logic follow the process diagram it was good to know the next step is a gateway and present the user a select list or what ever (dynamically) - like v4.
