### ISSUE TITLE
Rename navigation

### ISSUE THREAD

**Issue by commi235** [mt-ag/apex-flowsforapex#130]
1. Getting Started
2. Diagram Management
3. Process Modeling
4. Process Instances

**Comment by rallen2010** [comment]
Can we go with

1. Getting Started
2. Diagram Management (Diagram Manager ? )
3. Flow Modeler (as before)
4. Flow Control (as before)

There is a lot of doc, tutorials, training material to change if we rename Flow Modeller and Flow Control in an incremental release...

**Comment by LouisMoreaux** [comment]
Okay for me, I work on engine-app so I can make the changes when we have the final version.

**Comment by nielsdebr** [comment]
I'm still for "Flow Management". A flow = process = diagram. A flow can be modeled and instantiated. If we introduce "diagram", then we have to rename 3 and 4 to "Process modeler" and "Process control". Also, the product is called "Flows for APEX", so it fits better that way. Another point is that we have a "diagrams" running in production. A diagram sounds more "static" to me, so flow management is a better term, because the process is "flowing".

Just my 5 cents to it. :)

**Comment by LouisMoreaux** [comment]
Can I rename in engine-app with :
1. Getting Started
2. Flow Management
3. Flow Modeler
4. Flow Control

**Comment by nielsdebr** [comment]
Yes, please rename as such.
