### ISSUE TITLE
scrip task and execute_plsql() without session

### ISSUE THREAD

**Issue by arashEghtedar** [mt-ag/apex-flowsforapex#138]
https://github.com/mt-ag/apex-flowsforapex/blob/c247920cfbf4c55b4f3e05514d63807d806948a9/src/plsql/flow_plsql_runner_pkg.pkb#L63

hi.
when we call a flow with a script task,  from a non apex session context , we get below error:

Error during flow_plsql_runner_pkg.run_task_script. SQLERRM: ORA-20987: APEX - Internal Error - Contact your application administrator.

**Comment by rallen2010** [comment]
Hi,  Yes we're aware of this - it's the same problem as #107.  Because there is no APEX session present, you can't do an APEX_EXEC to run the PL/SQL.  The solution is issue #116, which will allow you to specify that a script task runs as plain pl/sql.  Scheduled to be fixed in V5.1 - should be released next few weeks.
