### ISSUE TITLE
Process Plug-in Manage Flow Instance Step

### ISSUE THREAD

**Issue by commi235** [mt-ag/apex-flowsforapex#163]
Create a process plugin which makes it even easier to integrate Flows for APEX.
Single responsibility should be taking process_id and subflow_id from application / page item and calling complete_step.

**Comment by madmexx2002** [comment]
Nice to have.
Same for process variables? Gateway, flow and Conditions for the gateway can then be set more declarative.

**Comment by rallen2010** [comment]
If you have a tightly coupled process, where the page submit should also call complete_step and branch to another page which implements the next process step, would the plugin return branching info?

**Comment by commi235** [comment]
My initial idea was to separate this into two plugins.
One you would hook into "Processing" the other into "After Processing" (aka branching).
That way you integrate isolated modules or building blocks onto the page.

Currently I can think of:
- complete step
- branch to next task ( what to do if not a user task?)
- set gateway variable

**Comment by nielsdebr** [comment]
I agree, offering multiple plug-ins will keep it more flexible, although the "set gateway variable" functionality could be integrated in both "complete step" as well as "branch to next task".

**Comment by commi235** [comment]
Combining things will make them more complex.
And looking at APEX, there's processes, computations and branches clearly separated from each other.

**Comment by nielsdebr** [comment]
Yes, but I can set a page item upon branching. :)

**Comment by commi235** [comment]
Process Plugin should include automatic branching, because we will not have branch plugins.

**Comment by LouisMoreaux** [comment]
Start working on the complete step plugin and I need some feedbacks.
![image](https://user-images.githubusercontent.com/42840524/112182245-699fd000-8bfd-11eb-9c03-ba95da34eede.png)

1. How process_id and subflow_id is define in the plugin, I have already implemented page item and looking at SQL query. Do you think we need more options?
2. It is possible to provide a route for a gateway inside the process plugin. Thanks for the suggestion @nielsdebr, if you leave Gateway field empty, it will use next gateway otherwise you can specified it. Last field is for route, for now it is just a text field but we can add some options (page item for example)
3. For branching, we just have to look at the next subflow step if it's a user task? So we redirect only if we complete a task and this task is immediatly followed by another user task?

**Comment by commi235** [comment]
1. I would think Page / Application Item should be enough here. Bonus points for SQL.
2. How does this work? It's calling flow_variables.set_var... I assume.
3. Include a switch to enable "Auto-Branching", if set to yes
    - If active task after complete_step is a userTask use apex_util.redirect_url
    - else do nothing

**Comment by madmexx2002** [comment]
Hi

If the process diagram is based on lanes the Auto-Branching should check if next userTask is on same lane.

**Comment by LouisMoreaux** [comment]
1. Thank you, I will focus on item and see if SQL is not too much work
2. Yes it's call flow_variables.set_var but it is just for defining route.
3. Thanks I will do that and take care of lanes !

**Comment by madmexx2002** [comment]
2. Set Gateway. For Inclusive Gateways maybe colon or comma separated list for multiple routes required.
3. Thx for taking care of lanes :)

**Comment by LouisMoreaux** [comment]
This plug-in can now manage a Flow Instance Step and performs these operations:
- Complete a step
- Reserve a step
- Release a step

**Comment by LouisMoreaux** [comment]
Included in version 21.1
