### ISSUE TITLE
Alternative view for BPMN-Viewer on page "Flow Monitor"

### ISSUE THREAD

**Issue by madmexx2002** [mt-ag/apex-flowsforapex#218]
For a better user experience on common screens the bpmn-viewer could be shown side-by-side with the reports. Function could be impleneted as option. See example how it will look on a 27" screen.
![image](https://user-images.githubusercontent.com/36326420/118096579-d3ed1980-b3d1-11eb-8346-628ac6a4c2cf.png)

**Comment by rallen2010** [comment]
Yes - I can absolutely see that an admin running 50+ simultaneous instances would want to do this -- and we did play with this during the last release cycle.  If you are monitoring a bunch of production processes, you can see enough about process state from the diagram, even if it is fairly small -- you can 'eye-ball it' and see if you have a problem.  
Maybe you would want to be able to click somewhere on the instance to get a almost-full screen modal view of the diagram so that you can see the detail, if you need to.  
Then if the modal also has the mouse-over details, that would get bonus marks!
We also have users with small screens who are just getting started with demos -- and we have to cater for both.
Is it possible in APEX to toggle the 'start new row for a region' at run-time so that you could accommodate both layouts in user preferences?

**Comment by madmexx2002** [comment]
In the preview i toolge at runtime with the button marked yellow. Next i will try to save it as preference and switch to it during page load.

**Comment by madmexx2002** [comment]
It is possible to save it as user preference und set it during the page load :)
_Modal view of diagram with details_: Diagram, process details, runtime history (who and when). This could be the output of extended logging features.
_...Then if the modal aslo has the mouse-over details..._ This would be very smart while coding the process, too. Just hover to see the name of the gateway or connection would be nice feature for the viewer plugin.
