### ISSUE TITLE
Flow Reset (1 Schritt)

### ISSUE THREAD

**Issue by koutsnGR** [mt-ag/apex-flowsforapex#220]
Es gibt keine funtionalität in ein Flow Prozesss nur ein Schritt zurück zu gehen.
Das Reset löscht den gantzen sub flow.

**Comment by koutsnGR** [comment]
Hallo,

Danke für die Schnelle Antwort.
Ich habe mich nicht Richtig ausgedrückt.
Meine Frage wäre, wenn ein Prozess mit Fehler endet, dann wurde ich gerne nur zu den früheren Prozesss Step gehen und nicht Alles zurücksetzen und wieder von Anfang anfangen.

**Comment by nielsdebr** [comment]
Reden wir hier über einen technischen oder einen fachlichen Fehler?

Vielleicht magst du den Flow mit uns teilen, damit wir den konkreten Fall besser verstehen?

**Comment by koutsnGR** [comment]
Beispiel:
![image](https://user-images.githubusercontent.com/81414783/118959821-f5ff1280-b962-11eb-81d3-fee6fc951d7b.png)

Der Prozess "Set option for exclusive Getway" ruft eine PL/SQL Routine. In diese habe ich absichtlich ein raise_application_error gemacht so dass, wir ein Fehler kriegen. 
Der Prozess ist jetzt in der  "Set option for exclusive Getway"  stehen geblieben.
Es wurde schön sein, wenn ich jetzt zurück zu "Timer" gehen konnte und nicht von Anfang ("Start") an starten müsste.
Das Reset löscht die Tabellen (flow_subflows und flow_subflow_log) für den Prozess und deswegen muss man von der Anfang den Prozess (FLow) wieder starten.

**Comment by rallen2010** [comment]
A few ideas here. (sorry - I don't speak German & am working from Google translate here!)
1.  If you want a timer, have you looked at using an Intermediate Catch Event with a Timer?
2.  Route B - must be complete in 10 sec -- you could set a Timer Boundary Event on this task to implement the timeout...
3.  Error handling inside scriptTasks.  Yes - we understand the problem here.  We have been looking at some ideas for handling errors in scriptTasks for a future release.
4.  Just a quick note that flow_reset is not intended to be used in production systems during normal running.  It's there for testing and possible administrator action.

**Comment by rallen2010** [comment]
I think these issues are all addressed in release 21.1 so I'm closing this ticket.
