### ISSUE TITLE
Clean up flow_api_pkg.

### ISSUE THREAD

**Issue by nielsdebr** [mt-ag/apex-flowsforapex#37]
- Some procedures are not needed, at least not in the spec.
- Merge flow_next_step with flow_next_branch
- "Helper" procedures should be moved to api_util_pkg.
- We need to separate the internal from the external API.
- A subflow_id as IN parameter should be sufficient to get the process_id, so there is no need to supply this parameter.

**Comment by commi235** [comment]
1. Removing ```process_id``` 
    Add ```default NULL``` for process_id parameter.  
    If NULL is supplied derive process_id based on sub_flow_id to go forward.  
    Else use supplied process_id.
2. Create a public API Package down to stepping through, creating, deleting and resetting

**Comment by rallen2010** [comment]
Question for discussion here.  

In V4.0, you use flow_next_step for every step that can be handled without the user's involvement.  The process only stops for the user to perform activities, and (incorrectly in bpmn terms) at exclusiveGateway and InclusiveGateway gateways for the user decision as a routing parameter on the  next_branch call.

In V5, we want to:
- get rid of next_branch, and make all process progression be triggered by a next_step
- not stop at gateway objects.  Gateways are really just railway-points / routers.  We already step through startEvents, stopEvents,  parallelGateways and gateway mergers without stopping at the points.  
- Move the decision-making task out of the gateway object.  The decisions need to be made either automatically from the underlying data, or if it requires a human decision, from a decision taken as a previous task and held in process variables.  A _Previous task_  shouldn't mean it has to be the activity immediately before the gateway -- although my V5 concept did that as it was the only way I could show the concept & that might be acceptable in V5.
- a next_step shouldn't have to know that it is the activity before a gateway, and then make a different call that includes the decision just because it happens to come before a gateway.  That would make building process in-box applications difficult and the processes inflexible as you would have to recode the task when you change the diagram.

My V5 concept demo just put a bpmn:scriptTask immediately before any  in/exclusive Gateway object.  The script built the forward_route parameter, and concluded by executing a next_step to step into the gateway, followed by a next_branch with the forward_route, to drive through the in/exclusive Gateway.  Fairly crude, but it worked for a concept demo.

I'm thinking that the definition of an inclusive or exclusive gateway should be able to tell the gateway that the branch information it needs is available from one of:
- a Process Variable
- a SQL expression where the process variables, inc the subject PK, are available
- a PL/SQl expression
- a PL/SQL function body
- ...this could end up being a subset of the server-side conditions list of clause types that we're familiar with
We don't have to implement all of this list in V5, but should have an architecture in mind that could incorporate these later, especially if Oracle get involved later.  They're all standard templates constructs that can be added into a piece of dynamically generated and executed PL/SQL - and they're templates so that they can be hardened from sql injection easily.

Minimum for V5.0, we should be able to have a gateway definition include which methiod it should use, and then be able compare a defined process variable and with the values in the forward path definition is equal to or contained in the variable specified by the gateway definition (method 1 above).  With that, and a piece of developer-written PL/SQL in a script task somewhere earlier in the process, any schema or process data could be processed by the script and left in a process variable as a decision that can be used for routing at the gateway.

More sophisticated solutions, for bonus points, could implement more of the spec types from my list in 5.0 or later.

Thoughts on this welcome (inc. 'please explain that again!' )

**Comment by nielsdebr** [comment]
For v5, I would always take the process value of the activity ID right before the gateway. If there is no value set, it would take the default path. If there is no default path, the status must be set to "error".

For v6, we have to enhance the properties panel for the gateway saying "Where is my value coming from?" with options like "Take the value of the activity before me" (default) or "PL/SQL Function" or "Static value", etc.

**Comment by rallen2010** [comment]
So this (approach 1) should behave in V5 like my demo did?

That was having a scriptTask immediately before an ex/inclusive gateway which used an app developer-supplied PL/SQl procedure to determine which routes to take.  The PL/Ql procedure then called next_step to go into the gateway, and then called next_branch, passing in the route it had built in the script.

This approach is easy, requires little UI work from us, but requires a developer to write a PL/SQl Procedure to drive the decision and then call the gateway.  

the existing next_branch functionality would still be in the product, callable by an app (as before) or by a script (as per my demo).

The next more complex approach (approach 2) would allow a gateway to get a decision from a process variable.  If not set, it would take the default path.  If no default, cause an error.

This requires us to do some UI work - as the gateway needs to be able to define which process variable it is going to look at for the decision.  
 (a) we need to parse the "default=<sequenceFlow_bpmn_id>" parameter off the bpmn:in/exclusiveGateway tag
 (b) Need to define and create flowsForApexExtensionElements variable  system using the bpmn.io extensible properties system.  Then add them to the Modeller UI, parse them from the XML, and use them in the modeller.

Approach 3:  If doing all of the work to add a variable system into the BPMN modeller is too scary / too much work, a quick & dirty workaround that could be easy used by an APEX developer would be to use an approach like that used in my demo for scripts and tasks.  After defining, saving & parsing a diagram, you would go into an APEX app to "register" the gateway & define parameters for it to use -- either linking it to a process variable, or defining a SQL statement or a PL/SQL function that could determine the route taken.  So essentially this replaces the need for a ScriptTask before the gateway with a more declarative approach (in APEX, rather than in BPMN Modeller).  This could give us great functionality fairly easily as it's all using technologies we are all comfortable with - APEX / Oracle / PL/SQL.

Approach 4 - Once you've figured out how to do approach 2, you could add SQL or PL/SQL expressions to the sequence flows & use them to make everything more declarative in the bpmn:modeller.  We should probably reserve this for later (Oracle?).

**Comment by rallen2010** [comment]
Ok, for the record, this is what I've done for V5.0:

1.  Each bpmn:inclusiveGateway and bpmn:exclusiveGateway will look for a process variable named 'Route:'<gateway-BPMN-id>  (example:  Route:Gateway_23454 ) which contains forward routing information that has been set by an earlier activity.  This activity could be a scriptTask immediately before the gateway, but doesn't have to be;  it could be set by some other activity step, APEX page, or scriptTask that has run earlier in the process.

For a bpmn:inclusiveGateway, the expected value is the single bpmn id of the chosen forward bpmn:sequenceFlow.  (for example: Flow_12345).

For a bpmn:exclusiveGateway, the expected value is a colon-delimited list of the (one or more) bpmn ids of the chosen forward bpmn:sequenceFlows.  (for example: Flow_12345:Flow54367:Flow65435 ).

2.  If the 'Route:'<gateway-BPMN-id> variable has not been set, the engine will look at the parsed BPMN diagram, and will chose the single forward path marked as the default path.

3.  If the 'Route:'<gateway-BPMN-id> variable has not been set AND there is no default path in the diagram, the flow engine will signal an error.

Step 1 has been implemented and will be in the code I check in shortly.  The check for default will be added once the data model is confirmed.

I have removed flow_next_branch from the API, other than to signal an error if it is called.

Applications should just issue a flow_next_step(process_id, Subflow_id) after completing each activity.  The engine will now proceed without stopping through any gateways -- except where it needs to wait for other activities to complete, for events, or when it has an error.
