### ISSUE TITLE
Process Inbox style apps with >1user/lane need a 'Step Assigned' mechanism

### ISSUE THREAD

**Issue by rallen2010** [mt-ag/apex-flowsforapex#52]
Process  Inbox style apps are easily built using the V5 functionality.  However, if more than one user is servicing a lane there is a problem that the process inbox shows all of the not-yet-completed tasks to everyone in the lane.  This would include a task that another user is currently working on -- which will result in multiple users picking up the same task to work on.

So we need to distinguish between a) current tasks that no one is currently working on ("available current task") , and b) current tasks that somebody is working on / has committed to work on ("assigned current task").

I can see several mechanisms for solving this problem:

1.  Add a sbfl_assigned_to column to flow_subflows.  Null allowed -- use of this whole mechanism should be optional.
2. create procedure flow_api_pkg.flow_assignment(pi_prcs_id, pi_sbfl_id, pi_user) that sets sbfl_assigned_to.  This would be called in an application when a user starts working on a task to say that "Hey, I'm working on this one!".
3.  We could split the subflow status 'running' into 2 separate statuses (stati?) - essentially 'running-available' and 'running-assigned' or leave it as it is.
4.  Adjust the existing views, etc.

FFA should work as it currently does if you choose to not use this mechanism -- you would only use if you have a process inbox style app & you have a pool (>1) of users servicing a single lane.  You would only need to use it on the steps done in multi-user lanes.

I think we should do 1, 2 & 4.

I think we need this / i can do this for V5.

**Comment by commi235** [comment]
For me this is where we should draw the line between the Flows-Engine and the business object.  
The lane information was only intended to serve as a reference towards other objects in the business object domain, e.g. a user group.  
If a task has been taken on by another user should be handled by the domain that also handles authentication and authorisation.  
Couple of questions we won't be able to answer because we don't do authentication and authorisation:  
Who is allowed to take over if another has been assigned to the task but no progress.  
Who are the right users to access this specific inbox.  
And probably a couple more issues.

**Comment by rallen2010** [comment]
Released in V5.0
