### ISSUE TITLE
Current object is not displayed in workflow loops

### ISSUE THREAD

**Issue by ArvidRegenberg** [mt-ag/apex-flowsforapex#55]
If you create a workflow with loops, the current object is not displayed (in color) if you have been there before. 
Two pictures for comparison are attached. It is probably just a "problem" for the demo application or maybe the plugin. 

The current object is "1".
Wrong behaviour:
![Flows_for_APEX_falsch](https://user-images.githubusercontent.com/38170646/95503347-888e0b00-09ab-11eb-8c73-3eeaa16c8450.png)

Correct behaviour
![Flows_for_APEX_richtig](https://user-images.githubusercontent.com/38170646/95503351-89bf3800-09ab-11eb-8070-c4d6d7abcdf1.png)

**Comment by rallen2010** [comment]
Hi Arvid,

Thanks for reporting this problem.

I understand what the problem is.  I fixed it 3 days ago…. for V5!     I’ve just tested it on V5 development code - where it is doing what it should be doing.  we have made some changes to the plugin for V5 which might affect it.

The problem is that the view which drives the status shading FLOW_PROCESS_VW makes a list of current,  last_completed, and other completed notes as 3 strings - which drive the shading in the client.

Let me see if that is back-portable to V4.

Regards,
Richard


Richard Allen
rallen2010@gmail.com

UK: +44 7758 155 930




On 8 Oct 2020, at 20:18, ArvidRegenberg <notifications@github.com> wrote:


If you create a workflow with loops, the current object is not displayed (in color) if you have been there before.
Two pictures for comparison are attached. It is probably just a "problem" for the demo application or maybe the plugin.

The current object is "1".
Wrong behaviour:
 <https://user-images.githubusercontent.com/38170646/95503347-888e0b00-09ab-11eb-8c73-3eeaa16c8450.png>
Correct behaviour
 <https://user-images.githubusercontent.com/38170646/95503351-89bf3800-09ab-11eb-8070-c4d6d7abcdf1.png>

**Comment by rallen2010** [comment]
By the way - what RDBMS version are you running?  There are RDBMS changes between 12.1 and 19c which affect this!  (listagg syntax changes).

**Comment by ArvidRegenberg** [comment]
I use 19c.
I have made a hotfix by changing the view of the sample application. 
For this I excluded all elements that appear in "current" from "completed". 

I add the code below and mark the change. But I am sure you can do it better. 

![hotfix](https://user-images.githubusercontent.com/38170646/95505725-233c1900-09af-11eb-9545-d601dd5ed048.png)

**Comment by rallen2010** [comment]
You got it - that's exactly the right thing to do.  It is fixed in V5 - so best to just carry on with your fix & you should be fine.  Is that OK?

**Comment by ArvidRegenberg** [comment]
Alright, thanks a lot! 

I am looking forward to V5.

**Comment by rallen2010** [comment]
sorry - actually - you need to change your subquery to add another where clause so that you only select the subflows in your current process ...
so .... not in (select sbfl_current from flow_subflows sbfl where sbfl.sbfl_current is not null and sbfl.sbfl_prcs_id = sflg.sflg_prcs_id)

**Comment by ArvidRegenberg** [comment]
Oh yes, I see the problem. Thanks for the advice!

**Comment by ArvidRegenberg** [comment]
Here is the complete changed code again, if anyone needs it. 

```SQL
CREATE OR REPLACE FORCE VIEW "FLOW_P0010_VW" ("DGRM_CONTENT", "PRCS_ID", "ALL_COMPLETED", "LAST_COMPLETED", "ALL_CURRENT") AS 
  with all_current as (
  select sbfl_prcs_id as prcs_id
       , listagg(sbfl_current, ':') within group ( order by sbfl_current ) as bpmn_ids
    from flow_subflows
   where sbfl_current is not null
group by sbfl_prcs_id
)
  , last_completed as (
  select sbfl_prcs_id as prcs_id
       , listagg(sbfl_last_completed, ':') within group ( order by sbfl_last_completed ) as bpmn_ids
    from flow_subflows
   where sbfl_last_completed is not null
group by sbfl_prcs_id
), 
all_completed as (
  select sflg.sflg_prcs_id as prcs_id
       , listagg(sflg.sflg_objt_id, ':') within group (order by sflg.sflg_objt_id) as bpmn_ids
    from flow_subflow_log sflg
   where sflg.sflg_objt_id not in ( select sbfl.sbfl_last_completed from flow_subflows sbfl where sbfl.sbfl_prcs_id = sflg.sflg_prcs_id )
     and sflg.sflg_objt_id not in ( select sbfl.sbfl_current from flow_subflows sbfl where sbfl_current is not null and sbfl.sbfl_prcs_id = sflg.sflg_prcs_id)
group by sflg.sflg_prcs_id
)
    select dgrm.dgrm_content
         , prcs.prcs_id
         , ( select acomp.bpmn_ids from all_completed acomp  where acomp.prcs_id = prcs.prcs_id ) as all_completed
         , ( select lcomp.bpmn_ids from last_completed lcomp where lcomp.prcs_id = prcs.prcs_id ) as last_completed
         , ( select acurr.bpmn_ids from all_current acurr    where acurr.prcs_id = prcs.prcs_id ) as all_current
      from flow_diagrams dgrm
      join flow_processes prcs
        on dgrm.dgrm_id = prcs.prcs_dgrm_id
with read only
/

```
