### ISSUE TITLE
orphan non-interrupting boundary timers

### ISSUE THREAD

**Issue by commi235** [mt-ag/apex-flowsforapex#80]
non-interrupting boundary events attached to a subflow are not cleaned up properly.
The created subflow for that specific timer is not removed after the sub flow it is attached to ends.

**Comment by rallen2010** [comment]
This bug affected Escalation & Error Boundary Events that caused a terminate on the main path through a sub-process, while there was a running non-interrupting timer running on the sub-process.  The non0interrupting timer was being left intact when the sub-process terminated, and its process moved on to the interrupting error or escalation boundary event.
The bug is fixed with this commit.
